### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ocefpaf** [kylepollina/mlo_co2#1]
Also, the readme is not in the tarball making it impossible to install from source.

**Comment by kylepollina** [comment]
Ah, I wasn't aware of this, I guess I never tried. I will make a fix

**Comment by ocefpaf** [comment]
BTW, while you are at it :smile:, the python version classifiers don't really do anything to tell installers what python version should be used. You will need the https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires in your `setup.py`.

PS: we try to keep some packaging best practices in https://github.com/ioos/ioos-python-package-skeleton, feel free to copy anything from there if you like it.

**Comment by kylepollina** [comment]
Updated with the fixes, thanks for the suggestions!
